# Generated by Django 4.1.2 on 2023-02-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_minuman_pakaian_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pakaian',
            old_name='kodepkn',
            new_name='kodepakaian',
        ),
    ]
